### ISSUE TITLE
AV1 issue with libaom 3.2.0 on Debian 11 against Google Chrome

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1676] opened 2021-12-05 17:19 UTC
When I make a video call using AV1 codec from Debian 11 where baresip is build with libaom 3.2.0 to Google Chrome 96.0, video window does not become visible and I baresip produces to log these kind of messages:
```
foo@test.tutpro.com: Call answered: sip:test@test.tutpro.com
stream: update 'audio'
stream: receive: setting SSRC: e75f2df4
stream: update 'video'
stream: receive: setting SSRC: 179e8320
audio: Set audio decoder: opus 16000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: opus 16000Hz 1ch
webrtc_aec: creating shared state: [16000 Hz, 1 channels, blocksize 160 samples]
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> webrtc_aec ---> opus
audio rx pipeline:        alsa <--- webrtc_aec <--- opus
Set video encoder: AV1  (500000 bit/s, 15.00 fps)
Set video decoder: AV1 
v4l2: /dev/video0: found valid V4L2 device (640 x 480) pixfmt=YUYV
v4l2: Current input: "Camera 1"
v4l2: current framerate is 30.00 fps
video tx pipeline:       v4l2 ---> selfview_pip ---> AV1
video rx pipeline:     (disp) <--- selfview_pip <--- AV1
foo@test.tutpro.com: Call established: sip:test@test.tutpro.com
stream: incoming rtp for 'audio' established, receiving from 192.26.134.10:60020
stream: incoming rtp for 'video' established, receiving from 192.26.134.10:60062
av1: decode error: Unspecified internal error0/0.0    
     
av1: decode error: Unspecified internal error
     
av1: decode error: Unspecified internal error0/0.0    
     
av1: decode error: Unspecified internal error0/0.0    
     
av1: decode error: Unspecified internal error
     
av1: decode error: Unspecified internal error0/0.0    
     
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     Truncated packet
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
call: terminate call '26b3ea8e9c34d3b6' with sip:test@test.tutpro.com
```
When I change baresip video codec to VP9, video calls works fine. Edit:  Same errors appear also in AV1 calls between two Debian 11 baresips.

**Comment by juha-h** [comment] 2021-12-05 17:34
I noticed that when I build baresip on Debian 11, I get this kind of warning:
```
  LD      baresip
/usr/bin/ld: warning: libaom.so.0, needed by /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libavcodec.so, may conflict with libaom.so.3
```
That is due to the fact that I have two libaoms installed:
```
$ dpkg -l | grep libaom
ii  libaom-dev:amd64                      3.2.0-1~bpo11+1                 amd64        AV1 Video Codec Library -- Development Files
ii  libaom0:amd64                         1.0.0.errata1-3                 amd64        AV1 Video Codec Library
ii  libaom3:amd64                         3.2.0-1~bpo11+1                 amd64        AV1 Video Codec Library
```
and libaom0 cannot be removed because lots of other Debian packages depend on it.  Does this mean that current av1 module that does not compile with libaom-dev (1.0.0.errata1-3)  cannot be installed on Debian 11?

**Comment by juha-h** [comment] 2021-12-06 08:09
I managed to get rid of the linker warning by specifying in av1/module.mk:
```
$(MOD)_LFLAGS	+= -l:libaom.a
```
but it didn't have any effect on the errors during a test call.

**Comment by alfredh** [comment] 2021-12-07 09:36
the problem is not the codec itself, it is a problem with the packetization.

**Comment by juha-h** [comment] 2021-12-07 16:30
Alfred E. Heggestad writes:

> the problem is not the codec itself, it is a problem with the
> packetization.

OK.  Is there something that can be done about it or should I close
these two issues?

**Comment by alfredh** [comment] 2021-12-08 10:20
I will have a look.

This ticket is duplicate btw:

https://github.com/baresip/baresip/issues/1677

**Comment by alfredh** [comment] 2021-12-11 19:05
I have tested with baresip-webrtc [1] and chrome:

Chrome Version 96.0.4664.93 (Official Build) (x86_64)


decoding (chrome to baresip) seems to work. encoding is not working.

```
av1: decode: header:  [M]  z=0  y=0  w=2  n=1
video: receiving with resolution 640 x 480 and format 'yuv420p'
sdl: created renderer 'metal'
av1: decode: header:  [M]  z=0  y=0  w=1  n=0
av1: decode: header:  [ ]  z=0  y=1  w=1  n=0
av1: decode: header:  [ ]  z=1  y=1  w=1  n=0
av1: decode: header:  [ ]  z=1  y=1  w=1  n=0
av1: decode: header:  [ ]  z=1  y=1  w=1  n=0
av1: decode: header:  [M]  z=1  y=0  w=1  n=0
av1: decode: header:  [M]  z=0  y=0  w=1  n=0
av1: decode: header:  [ ]  z=0  y=1  w=1  n=0
av1: decode: header:  [M]  z=1  y=0  w=1  n=0
av1: decode: header:  [M]  z=0  y=0  w=1  n=0
av1: decode: header:  [M]  z=0  y=0  w=1  n=0
av1: decode: header:  [M]  z=0  y=0  w=1  n=0
av1: decode: header:  [ ]  z=0  y=1  w=1  n=0
av1: decode: header:  [M]  z=1  y=0  w=1  n=0
```

if the video decode fails, the baresip core should ask the remote peer for a new keyframe.
is this happening with you ?




[1] https://github.com/baresip/baresip-webrtc

**Comment by alfredh** [comment] 2021-12-11 19:15
btw, you also need to load a video display module, for example sdl.so or x11.so

if there is packet loss during the call setup, the first keyframe might be lost.
it is therefore important to ask for a new one, or to wait for the next keyframe interval.

**Comment by juha-h** [comment] 2021-12-12 09:23
WIth VP9 codec (that works) between two Debian 11 baresips, I first get Unspecified internal errors, but after a couple of seconds they disappear and video starts working:
```
video tx pipeline:       v4l2 ---> selfview_pip ---> VP9
video rx pipeline:     (disp) <--- selfview_pip <--- VP9
video: start display
call: stream start (active=1)
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1)
audio: start
video: update
stream: audio: enable RTP from remote
stream: video: enable RTP from remote
test@lab.tutpro.com: Call established: sip:jh@lab.tutpro.com
presence: ua=0x55c93d7b0f50 got event 14 (CALL_ESTABLISHED)
stream: incoming rtp for 'audio' established, receiving from 192.26.111.29:60100
presence: ua=0x55c93d7b0f50 got event 21 (CALL_RTPESTAB)
stream: incoming rtp for 'video' established, receiving from 192.26.111.29:60132
presence: ua=0x55c93d7b0f50 got event 21 (CALL_RTPESTAB)
vp9: decode error: Unspecified internal error0/0.0    
vp9: decode error: Unspecified internal error
vp9: decode error: Unspecified internal error
vp9: decode error: Unspecified internal error0/0.0    
vp9: decode error: Unspecified internal error
vp9: decode error: Unspecified internal error
...
vp9: decode error: Unspecified internal error0/0.0    
vp9: decode error: Unspecified internal error
vp9: decode error: Unspecified internal error
video: receiving with resolution 640 x 480 and format 'yuv420p'
x11: shared memory enabled
```
With AV1 codec, after the initial Unspecified internal errors, I start to get other decode errors and video never starts working:
```
Set video encoder: AV1  (1000000 bit/s, 30.00 fps)
Set video decoder: AV1 
video: start source
v4l2: /dev/video0: found valid V4L2 device (640 x 480) pixfmt=YUYV
v4l2: Current input: "Camera 1"
v4l2: current framerate is 30.00 fps
video tx pipeline:       v4l2 ---> selfview_pip ---> AV1
video rx pipeline:     (disp) <--- selfview_pip <--- AV1
video: start display
call: stream start (active=1)
opus: encoder fmtp (minptime=10;useinbandfec=1)
audio: start
video: update
stream: audio: enable RTP from remote
stream: video: enable RTP from remote
test@lab.tutpro.com: Call established: sip:foo@lab.tutpro.com
presence: ua=0x55c1ec667f50 got event 14 (CALL_ESTABLISHED)
stream: incoming rtp for 'audio' established, receiving from 192.26.134.10:60378
presence: ua=0x55c1ec667f50 got event 21 (CALL_RTPESTAB)
stream: incoming rtp for 'video' established, receiving from 192.26.134.10:60418
presence: ua=0x55c1ec667f50 got event 21 (CALL_RTPESTAB)
av1: decode error: Unspecified internal error0/0.0    
av1: decode error: Unspecified internal error
av1: decode error: Unspecified internal error
av1: decode error: Unspecified internal error0/0.0    
av1: decode error: Unspecified internal error
av1: decode error: Unspecified internal error
av1: decode error: Unspecified internal error
av1: decode error: Unspecified internal error
av1: decode error: Unspecified internal error
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
...
av1: decode error: Corrupt frame detected
     Truncated packet
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds
     No sequence header
av1: decode error: Corrupt frame detected
...
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     Truncated packet
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected  
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
...
```

**Comment by juha-h** [comment] 2021-12-12 11:09
In call from baresip on Debian 11 to Google Chrome, no video window is shown on Debian 11 and log shows similar errors as in above:
```
Set video encoder: AV1  (1000000 bit/s, 30.00 fps)
Set video decoder: AV1 
video: start source
v4l2: /dev/video0: found valid V4L2 device (640 x 480) pixfmt=YUYV
v4l2: Current input: "Camera 1"
v4l2: current framerate is 30.00 fps
video tx pipeline:       v4l2 ---> selfview_pip ---> AV1
video rx pipeline:     (disp) <--- selfview_pip <--- AV1
video: start display
call: stream start (active=1)
opus: encoder fmtp (minptime=10;useinbandfec=1)
audio: start
video: update
stream: audio: enable RTP from remote
stream: video: enable RTP from remote
test@test.tutpro.com: Call established: sip:foo@test.tutpro.com
presence: ua=0x5615a0956f50 got event 14 (CALL_ESTABLISHED)
stream: incoming rtp for 'audio' established, receiving from 192.26.134.10:60450
presence: ua=0x5615a0956f50 got event 21 (CALL_RTPESTAB)
stream: incoming rtp for 'video' established, receiving from 192.26.134.10:60478
presence: ua=0x5615a0956f50 got event 21 (CALL_RTPESTAB)
av1: decode error: Unspecified internal error0/0.0    
av1: decode error: Unspecified internal error0/0.0    
av1: decode error: Unspecified internal error0/0.0    
av1: decode error: Unspecified internal error0/0.0    
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected efps=0.0/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected efps=0.0/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected efps=14.1/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected efps=14.1/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected286989 (bit/s) efps=14.1/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected286989 (bit/s) efps=14.1/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected286989 (bit/s) efps=14.1/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected287768 (bit/s) efps=14.1/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected287768 (bit/s) efps=14.1/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected287768 (bit/s) efps=16.6/0.0    
     Truncated packet
presence: ua=0x5615a0956f50 got event 22 (CALL_RTCP)
av1: decode error: Corrupt frame detected287768 (bit/s) efps=16.6/0.0    
     Truncated packet
presence: ua=0x5615a0956f50 got event 22 (CALL_RTCP)/s) efps=16.6/0.0    
av1: decode error: Corrupt frame detected
     Truncated packet
av1: decode error: Corrupt frame detected340450 (bit/s) efps=16.6/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected340450 (bit/s) efps=16.6/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected340450 (bit/s) efps=16.6/0.0    
     Truncated packet
av1: decode error: Corrupt frame detected312842 (bit/s) efps=16.6/0.0    
     Truncated packet
...
```

**Comment by alfredh** [comment] 2021-12-14 08:31
we should try to find out if rtcp FIR/PLI is sent to request a new key frame:

1. decoder gets a decode error
2. decoder sends a RTCP FIR/PLI back to encoder
3. encoder receives FIR, forces a new keyframe
4. decoder receices the new keyframe and stops sending FIR/PLI

sending of FIR/PLI is done here:

```
static void send_fir(struct stream *s, bool pli)
```

receiving of FIR/PLI is here:

```c
static void rtcp_handler(struct stream *strm, struct rtcp_msg *msg, void *arg)
{
	struct video *v = arg;
	(void)strm;

	MAGIC_CHECK(v);

	switch (msg->hdr.pt) {

	case RTCP_FIR:
		v->vtx.picup = true;
		break;

	case RTCP_PSFB:
		if (msg->hdr.count == RTCP_PSFB_PLI) {

			lock_write_get(v->vtx.lock_enc);

			v->vtx.picup = true;

			lock_rel(v->vtx.lock_enc);
		}
		break;

	case RTCP_RTPFB:
		if (msg->hdr.count == RTCP_RTPFB_GNACK)
			v->vtx.picup = true;
		break;

	default:
		break;
	}
}
```

**Comment by alfredh** [comment] 2022-01-14 20:56
if you take a careful look at the code, you will notice a multi-threading bug;

only 1 case is protected with lock_write_get / lock_rel

did you manage to check if the keyframe request is working for this codec ?

**Comment by juha-h** [comment] 2022-01-15 09:53
Sorry, I don't know how to check if new keyframe is requested.

**Comment by alfredh** [comment] 2022-01-15 10:46
hi @juha-h 


can you try to add some debug printf to this function:

https://github.com/baresip/baresip/blob/master/src/video.c#L861


when a new keyframe is requested from the other side, the `update` flag should be
set to true here:

```c
int av1_encode_packet(struct videnc_state *ves, bool update,
		      const struct vidframe *frame, uint64_t timestamp)
```

**Comment by juha-h** [comment] 2022-01-15 13:21
I added `info` call after `L861` in video.c:
```
        case RTCP_PSFB:
		info("case RTCP_PSFB hdr.count = %d\n", msg->hdr.count); 
```
but did not get those info messages to Linux console during AV1 call between baresip and google chrome.

**Comment by alfredh** [comment] 2022-01-15 13:39
this means that we never receive the FIR (Full Intra Request) from the other side.
it could be because remote never sent it, or because it is lost in the network.


it would be interesting to make the following experiment:

- connect two laptops with baresip+av1

1. dial from A to B via your SIP provider
2. dial directly from A to B, i.e. ip-to-ip

and then observe if there is any difference ...

**Comment by juha-h** [comment] 2022-01-15 14:19
Alfred E. Heggestad writes:

> it would be interesting to make the following experiment:
> 
> - connect two laptops with baresip+av1
> 
> 1. dial from A to B via your SIP provider
> 2. dial directly from A to B, i.e. ip-to-ip
> 
> and then observe if there is any difference ...

There was no difference.  In second test, both baresips were on the
same WiFi network.

Calling baresip showed on console:

video tx pipeline:       v4l2 ---> selfview_pip ---> AV1
video rx pipeline:     (disp) <--- selfview_pip <--- AV1
***@***.***: Call established: ***@***.***
stream: incoming rtp for 'audio' established, receiving from 192.168.241.45:3584
stream: incoming rtp for 'video' established, receiving from 192.168.241.45:6416
av1: decode error: Unspecified internal error
     
av1: decode error: Unspecified internal error0/0.0    
     
av1: decode error: Unspecified internal error0/0.0    
     
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detecteds=0.0/0.0    
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header

and called baresip showed:

video tx pipeline:       v4l2 ---> selfview_pip ---> AV1
video rx pipeline:     (disp) <--- selfview_pip <--- AV1
stream: incoming rtp for 'video' established, receiving from 192.168.241.95:14400
av1: decode error: Unspecified internal error
     
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     Truncated packet
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     No sequence header
av1: decode error: Corrupt frame detected
     Truncated packet
av1: decode error: Corrupt frame detected
     No sequence header

**Comment by alfredh** [comment] 2022-01-20 17:05
@juha-h could you please update and try again ?

I made some fixes to the av1 decoder.


BTW, please note that you should also load a video display module, e.g. x11 or sdl ...

**Comment by juha-h** [comment] 2022-01-20 18:24
After pulling the latest changes from master, I build new Debian package.  Then I made a test call between two laptops on the same WiFi network first using VP9 to make sure that video display/source worked OK.  No problems with that.

Then I changed video codec to AV1.  Video did not work, but error messages on console had changed from the test with the previous version:
```
Set video encoder: AV1  (500000 bit/s, 15.00 fps)
Set video decoder: AV1 
v4l2: /dev/video0: found valid V4L2 device (640 x 480) pixfmt=YUYV
v4l2: Current input: "Camera 1"
v4l2: current framerate is 30.00 fps
video tx pipeline:       v4l2 ---> selfview_pip ---> AV1
video rx pipeline:     (disp) <--- selfview_pip <--- AV1
test@test.tutpro.com: Call established: sip:foo@test.tutpro.com
stream: incoming rtp for 'audio' established, receiving from 192.168.45.38:60206
stream: incoming rtp for 'video' established, receiving from 192.168.45.38:60232
av1: decode: unexpected obu type 4/s) efps=0.0/0.0    
av1: decode error [w=1, 7665 bytes]: Unspecified internal error ()
av1: decode error [w=1, 4713 bytes]: Unspecified internal error ()
av1: decode: unexpected obu type 4/s) efps=0.0/0.0    
av1: decode: unexpected obu type 4/s) efps=0.0/0.0    
av1: decode error [w=1, 5215 bytes]: Unspecified internal error ()
av1: decode: unexpected obu type 4(bit/s) efps=0.0/0.0    
av1: decode: unexpected obu type 4(bit/s) efps=0.0/0.0    
av1: decode: unexpected obu type 4(bit/s) efps=12.5/0.0    
av1: decode: unexpected obu type 4(bit/s) efps=12.5/0.0    
call: terminate call 'b26f2f520b00ec61' with sip:foo@test.tutpro.com2.8/0.0    
```
The other baresip reported similar errors.

**Comment by alfredh** [comment] 2022-01-21 18:23
thanks, I will have a look again at the encoder.


the av1 encoder and decoder are completely separate. I think the decoder is working as it should.

1. encode
2. decode

case:

1. baresip to baresip
2. baresip to chrome/av1


could you also try with chrome, and see if baresip is able to decode the video stream from chrome ?

**Comment by juha-h** [comment] 2022-01-21 19:13
Alfred E. Heggestad writes:

> the av1 encoder and decoder are completely separate. I think the
> decoder is woking as it should.
> 
> 1. encode
> 2. decode
> 
> case:
> 
> 1. baresip to baresip
> 2. baresip to chrome/av1
> 
> could you also try with chrome, and see if baresip is able to decode
> the video stream from chrome ?

I tried baresip on Debian against chrome.  baresip showed both selfview
and video from chrome, but chrome showed only selfview, i.e., not video
from baresip.  In spite of showing video from chrome, baresip console
listed many decode errors (corrupt frame detected).

Again, no problems with VP9.

**Comment by alfredh** [comment] 2022-01-24 10:34
I found the problem why the first keyframe is not received. I tested between two machines
on the local network. The first RTP packet that is decoded has a sequence number that
is around 40-50 packets behind the first sequence number. All packets arrive on the host
(verified with Wireshark). This means that the first 40-50 video RTP packets are dropped
inside baresip, which should not happen.

I found this code:

```
iff --git a/src/stream.c b/src/stream.c
index 5741e79..4c48da2 100644
--- a/src/stream.c
+++ b/src/stream.c
@@ -1138,8 +1138,6 @@ void stream_flush(struct stream *s)
 
        if (s->rx.jbuf)
                jbuf_flush(s->rx.jbuf);
-
-       rtp_clear(s->rtp);
 }
 ```

if I remove the call to rtp_clear, the first video packet arrives as expected
and no packets are lost.

@juha-h could you also please test again between baresip-to-baresip ?

**Comment by juha-h** [comment] 2022-01-24 12:58
Alfred E. Heggestad writes:

> @juha-h could you also please test again between baresip-to-baresip ?

I made AV1 test calls between two Debian 11 baresips.  Calling baresip
first produced a punch of unspecified internal errors to console, but
after that video started to flow both ways.
```
Set video encoder: AV1  (500000 bit/s, 15.00 fps)
Set video decoder: AV1 
v4l2: /dev/video0: found valid V4L2 device (640 x 480) pixfmt=YUYV
v4l2: Current input: "Camera 1"
v4l2: current framerate is 30.00 fps
video tx pipeline:       v4l2 ---> selfview_pip ---> AV1
video rx pipeline:     (disp) <--- selfview_pip <--- AV1
***@***.***: Call established: ***@***.***
stream: incoming rtp for 'audio' established, receiving from 192.26.45.126:60172
stream: incoming rtp for 'video' established, receiving from 192.26.45.126:60194
av1: decode error [w=0, 6117 bytes]: Unspecified internal error ()
av1: decode error [w=0, 1641 bytes]: Unspecified internal error ()
av1: decode error [w=0, 2765 bytes]: Unspecified internal error ()
av1: decode error [w=0, 2523 bytes]: Unspecified internal error ()
av1: decode error [w=0, 2371 bytes]: Unspecified internal error ()
av1: decode error [w=0, 2580 bytes]: Unspecified internal error ()
av1: decode error [w=0, 2886 bytes]: Unspecified internal error ()
av1: decode error [w=0, 3032 bytes]: Unspecified internal error ()
av1: decode error [w=0, 4301 bytes]: Unspecified internal error ()
av1: decode error [w=0, 6263 bytes]: Unspecified internal error ()
av1: decode error [w=0, 15168 bytes]: Unspecified internal error ()
av1: decode error [w=0, 7189 bytes]: Unspecified internal error ()
av1: decode error [w=0, 6678 bytes]: Unspecified internal error ()
av1: decode error [w=0, 7527 bytes]: Unspecified internal error ()
av1: decode error [w=0, 5284 bytes]: Unspecified internal error ()
av1: decode error [w=0, 5061 bytes]: Unspecified internal error ()
av1: decode error [w=0, 3385 bytes]: Unspecified internal error ()
av1: decode error [w=0, 5506 bytes]: Unspecified internal error ()
av1: decode error [w=0, 6207 bytes]: Unspecified internal error ()
av1: decode error [w=0, 4459 bytes]: Unspecified internal error ()
av1: decode error [w=0, 8082 bytes]: Unspecified internal error () 
av1: decode error [w=0, 9218 bytes]: Unspecified internal error () 
av1: decode error [w=0, 8078 bytes]: Unspecified internal error () 
av1: decode error [w=0, 8958 bytes]: Unspecified internal error () 
video: receiving with resolution 640 x 480 and format 'yuv420p'    
x11: shared memory enabled
```

**Comment by juha-h** [comment] 2022-01-24 13:06
I also tested Debian 11 baresip against Chrome.  That did not work.  In
incoming calls unspecified internal errors did not stop and decoder also
reported "could not decode OBU: Bad message" errors.  In outgoing calls
now errors were reported on console, but video didn't show up either.

**Comment by alfredh** [comment] 2022-01-24 19:12
thanks!

can you please also comment out the call to rtp_clear, and make a test ?
please check if the remote image comes up in the start.

I am struggeling to get the AV1 packetization correct.
it has to decode all OBUs from the encoder, and rewrite them with slightly different
parameters. I wish there was a simpler solution.

**Comment by juha-h** [comment] 2022-01-24 19:29
I made this:
```
diff --git a/src/stream.c b/src/stream.c
index 5741e798..c85c6f7b 100644
--- a/src/stream.c
+++ b/src/stream.c
@@ -1139,7 +1139,7 @@ void stream_flush(struct stream *s)
    if (s->rx.jbuf)
        jbuf_flush(s->rx.jbuf);
 
-   rtp_clear(s->rtp);
+   //  rtp_clear(s->rtp);
 }
```
Video did not show up in the calling baresip, until the  `Unspecified internal error ()` messages stopped to appear.

**Comment by alfredh** [comment] 2022-01-28 12:05
@juha-h want to make another test with git HEAD ?

**Comment by juha-h** [comment] 2022-01-28 14:53
In Debian - Debian test, video worked both ways after initial
```
av1: decode error [w=0, 2729 bytes]: Unspecified internal error ()
```
errors at caller disappeared.  No errors showed up at callee.

In Debian -> Chrome test, video worked at caller, but callee only displayed selfview.  Caller console initially showed same decode errors as in above, but later they turned to other kind of decode errors:
```
stream: incoming rtp for 'video' established, receiving from 192.26.144.65:60066
av1: decode error [w=1, 2482 bytes]: Unspecified internal error ()
av1: decode error [w=1, 2401 bytes]: Unspecified internal error ()
av1: decode error [w=1, 2178 bytes]: Unspecified internal error ()
av1: decode error [w=1, 1592 bytes]: Unspecified internal error ()
av1: decode error [w=1, 1512 bytes]: Unspecified internal error ()
video: receiving with resolution 640 x 480 and format 'yuv420p'
x11: shared memory enabled
av1: decode error [w=1, 7750 bytes]: Corrupt frame detected (Failed to decode tile data)
av1: decode error [w=1, 9063 bytes]: Corrupt frame detected (Keyframe / intra-only frame required to reset decoder state)
av1: decode error [w=1, 8553 bytes]: Corrupt frame detected (Keyframe / intra-only frame required to reset decoder state)
av1: decode error [w=1, 12680 bytes]: Corrupt frame detected (Keyframe / intra-only frame required to reset decoder state)
...
```
In Chrome -> Debian test I may have some other issues, since VP9 does not work either (like it does work in Debian -> Chrome test).

**Comment by alfredh** [comment] 2022-01-28 17:03
I have tested with this project: (no SIP signaling)

https://github.com/baresip/baresip-webrtc

and it is working also with AV1.

so it is strange that it does not work in your SIP environment.
if your setup includes SIP/RTP Proxy it might be good to try to exclude some items
to make the system more simple. For example make a local direct call, excluding any proxies.

perhaps you could also test the baresip-webrtc project ?

**Comment by juha-h** [comment] 2022-01-28 17:26
Yes, there may be some issue with my SIP Proxy/rtpengine regarding Chrome/WebRTC.  But then why Debian -> Chrome test works fine when I use VP9 or H264 instead of AV1?  And why do I get initial `av1: decode error [w=1, 2482 bytes]: Unspecified internal error ()` also in Debian -> Debian test?

Anyway, you can close this issue if AV1 with libaom 3.2.0 works in your tests without errors.

**Comment by alfredh** [comment] 2022-01-28 23:06
there should not be any warnings about decode error, unless something is wrong.

we should make a local-test between 2 machines, to exclude problems with SIP/RTP proxy.


When using rtp-engine, there is a problem with sending the first keyframe.
since both A and B are behind NAT (most likely), each client has to send an outbound RTP packet
to the rtp-engine, before it can receive anything. any inbound packets sent before that will
be dropped by the NAT box.

in the beginning of the call, the rtp-engine will receive a full Keyframe from e.g. A
but at this time, B did not send any packets yet. So the rtp-engine does not know where to send
the RTP packets from A. He either has to save them, or drop them.

this is the same for all video codecs, perhaps AV1 is more chatty than VP9.

if you know the author of rtp-engine perhaps you can ask him how this scenario is handled.

**Comment by juha-h** [comment] 2022-01-29 07:17
Alfred E. Heggestad writes:

> there should not be any warnings about decode error, unless something
> is wrong. 
> 
> we should make a local-test between 2 machines, to exclude problems
> with SIP/RTP proxy.

That surely would help in determining what the cause of the initial
errors are.

> When using rtp-engine, there is a problem with sending the first keyframe.
> since both A and B are behind NAT (most likely), each client has to
> send an outbound RTP packet to the rtp-engine, before it can receive
> anything. any inbound packets sent before that will be dropped by the
> NAT box.

> in the beginning of the call, the rtp-engine will receive a full
> Keyframe from e.g. A but at this time, B did not send any packets
> yet. So the rtp-engine does not know where to send 
> the RTP packets from A. He either has to save them, or drop them.

Yes, I don't know if rtpengine is able to queue the first packet before it
knows where to send it.

> this is the same for all video codecs, perhaps AV1 is more chatty than
> VP9.

That is what I thought too.

I just made another AV1 test, this time between my Android baresip app
and Debian baresip.  Now Debian console didn't show any errors no matter
if Debian baresip made or answered the call and video worked both ways.

Android log on the other hand, showed lots of messages like this:
```
01-29 09:11:45.038 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6856, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.042 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6857, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.042 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6858, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.042 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6859, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.125 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6860, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.125 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6861, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.184 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6862, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.240 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6863, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.285 20558 20645 D Baresip+ Lib: av1: encode: copy [type=6 (OBU_FRAME) x=0 s=1 size=35869]
01-29 09:11:45.296 20558 20645 D Baresip+ Lib: av1: decode: header:  [ ]  [seq=6864, 1279 bytes]  z=1  y=1  w=0  n=0
01-29 09:11:45.301 20558 20645 D Baresip+ Lib: av1: decode: header:  [M]  [seq=6865,  762 bytes]  z=1  y=0  w=0  n=0
01-29 09:11:45.356 20558 20645 D Baresip+ Lib: av1: decode: header:  [M]  [seq=6866,  855 bytes]  z=0  y=0  w=0  n=0
01-29 09:11:45.356 20558 20645 D Baresip+ Lib: av1: decode: copy [type=6 (OBU_FRAME) x=0 s=0 size=852]
01-29 09:11:45.356 20558 20645 D Baresip+ Lib: av1: decode error [w=0, 857 bytes]: Unspecified internal error ()
```
But they may be due to camera input queue getting full:
```
01-29 09:11:46.327 20558 20645 D Baresip+ Lib: [android_camera @ 0x7307b0b980] Input queue was full, dropping frame, consider raising the input_queue_size option (current value: 5)
```

**Comment by juha-h** [comment] 2022-01-29 07:24
juha-h writes:

> But they may be due to camera input queue getting full:
> ```
> 01-29 09:11:46.327 20558 20645 D Baresip+ Lib: [android_camera @ 0x7307b0b980] Input queue was full, dropping frame, consider raising the input_queue_size option (current value: 5)
> ```

When I changed codec from AV1 to VP9, no log messaged showed up on
Android (nor Debian) console and video between Android and Debian worked
very smoothly.  Perhaps AV1 is simply too heavy codec and does not work
properly without hardware assistance.

**Comment by alfredh** [comment] 2022-01-29 09:03
please note that the AV1 codec module is experimental. I am expected many improvements
in the libaom libraries in the next years, also including hardware support and also
other better libraries such as rav1e and ffmpeg.

I will close the issue for now.

**Closed by alfredh** 2022-01-29 09:03 UTC
Labels: bug, Video
