### ISSUE TITLE
Bad totag sent by baresip in the ACK and BYE 

### ISSUE THREAD

**Issue by JuanPascual2** [baresip/baresip#2819] opened 2023-11-27 21:50 UTC
Hello
Baresip sends the totag received in the temporary response:180 Ringing in the ACK and BYE.
Baresip should send the totag received in the response:200 OK.

Below are the sip traces:
BR
Juan
[badtotag.txt](https://github.com/baresip/baresip/files/13480729/badtotag.txt)

**Comment by alfredh** [comment] 2023-12-02 12:15
why are you sending two different To tags in 180 and 200 ?

If I can remember correctly, that should be two different dialogs ?

Please also include config and log file, like stated here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by JuanPascual2** [comment] 2023-12-02 13:44
Hello
This is the actual behaviour of an oracle SBC.
Changing the totag permits modify the SDP offer between 180 Ringing and 200 OK.
The SDP offer is modified during the hunting list service. 

BR
Juan
[config.txt](https://github.com/baresip/baresip/files/13536410/config.txt)
[account.txt](https://github.com/baresip/baresip/files/13536411/account.txt)

**Comment by JuanPascual2** [comment] 2023-12-04 10:04
[logbarersip.txt](https://github.com/baresip/baresip/files/13544510/logbarersip.txt)
Attached baresip log.
@juha-h, the tagto is often different when music is played during the ringing phase.

**Comment by juha-h** [comment] 2023-12-05 02:42
Looks to me that 1xx response with To tag creates an early dialog and
that 2xx response either confirms the early dialog (if To tag matches)
or creates a new confirmed dialog.  In the latter case, the early dialog
is then terminated.  See
https://www.rfc-editor.org/rfc/rfc3261#section-13.2.2.1 and
https://www.rfc-editor.org/rfc/rfc3261#section-13.2.2.4.

**Comment by maximilianfridrich** [comment] 2023-12-05 10:28
I believe this is related to https://github.com/baresip/baresip/issues/2114.

The fix I provided for this had to be reverted because it resulted in some ACKs not being sent, see https://github.com/baresip/baresip/issues/2772.

I just opened a new PR in re that should fix this: https://github.com/baresip/re/pull/1023. I tested it with a SIPP scenario and the tags are correct and ACKs are being sent.

However, the ACK issue was a little confusing, I believe this should be tested in a few different setups to ensure that ACKs are always sent correctly.

**Comment by alfredh** [comment] 2023-12-06 09:22
thanks Maximilian,

hi @JuanPascual2 could you please test the patch from him ?

**Comment by JuanPascual2** [comment] 2023-12-06 11:11
Hello
[re-forking_100rel_log.txt](https://github.com/baresip/baresip/files/13579907/re-forking_100rel_log.txt)
I tested the re_forking_100rel branch.
The test is ok, baresip sends the 200OK totag in the ACK and in the BYE. 
Attached are the traces and logs

**Comment by JuanPascual2** [comment] 2023-12-06 11:47
Branch tested
https://github.com/maximilianfridrich/re/tree/forking_100rel

**Comment by maximilianfridrich** [comment] 2023-12-07 07:41
@juha-h Could you try https://github.com/baresip/re/pull/1023 in your setup which led to the ACK issues with re-INVITEs (from https://github.com/baresip/baresip/issues/2772)? I want to make sure we don't introduce any regressions with this.

**Comment by juha-h** [comment] 2023-12-08 02:20
Maximilian Fridrich writes:

> @juha-h Could you try https://github.com/baresip/re/pull/1023 in your
> setup which led to the ACK issues with re-INVITEs (from
> https://github.com/baresip/baresip/issues/2772)? I want to make sure
> we don't introduce any regressions with this.

My Internet connection is currently so bad that I cannot get to GitHub.
Will try later.

**Comment by juha-h** [comment] 2023-12-09 07:51
I gave [baresip/re#1023](https://github.com/baresip/re/pull/1023) a try and no ack to 200 ok of re-invite.  There is nothing special in my test.  Normal call between two baresips and then x:
```
[0:00:47] audio=24554/24391 video=0/0 (bit/s) efps=0.0/0.0    call: hold sip:jh@test.tutpro.com
09:44:23.195#
TCP 192.168.243.45:47834 -> 192.168.243.45:5060
INVITE sip:jh@test.tutpro.com;gr=urn:uuid:9b21c1a8-dc58-a3d6-83d5-7be67cbe70ce SIP/2.0
Via: SIP/2.0/TCP 192.168.243.45:47834;branch=z9hG4bK20532738bbbd92b3;rport
Contact: <sip:test@test.tutpro.com;gr=urn:uuid:18ffb445-ce14-78c2-8c2e-6ffd34e4a275>
Max-Forwards: 70
Proxy-Authorization: Digest username="test", realm="test.tutpro.com", nonce="ZXQb0WV0GqWB3Fae4hRKPX2dkp6neeSfkRDh+r3aSCTjWMTTAxSVuEM4LKWA", uri="sip:jh@test.tutpro.com;gr=urn:uuid:9b21c1a8-dc58-a3d6-83d5-7be67cbe70ce", response="911b06d657b07ffb0f70b39fab4504bb", cnonce="6f691dc17497e331", qop=auth, nc=00000004, algorithm=MD5
Route: <sip:192.168.243.45;transport=tcp;lr>
To: <sip:jh@test.tutpro.com>;tag=1f8b9d4cb834cba0
From: "Test Account" <sip:test@test.tutpro.com>;tag=2ed65afad3ac72b2
Call-ID: bb34024e3d14921e
CSeq: 3306 INVITE
User-Agent: baresip v3.7.0 (x86_64/Linux)
Content-Type: application/sdp
Content-Length: 1192

v=0
o=- 2879399927 1029791592 IN IP4 192.168.243.45
s=-
c=IN IP4 192.168.243.45
t=0 0
m=audio 37312 RTP/AVP 98 99 9 0 8 101 102 103 104 9 18
a=rtpmap:98 AMR-WB/16000
a=rtpmap:99 AMR/8000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=rtpmap:102 CODEC2/8000
a=rtpmap:103 opus/48000/2
a=fmtp:103 stereo=0;sprop-stereo=0;maxaveragebitrate=28000;cbr=0;useinbandfec=1
a=rtpmap:104 G7221/16000
a=fmtp:104 bitrate=32000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=sendonly
a=rtcp-rsize
a=ssrc:3883150684 cname:sip:test@test.tutpro.com
a=minptime:20
a=ptime:20
a=label:1
a=mid:0
m=video 14142 RTP/AVP 96 97 98 99 100
a=rtpmap:96 VP9/90000
a=fmtp:96 max-fs=3600;profile-id=0
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=0;profile-level-id=42e01f
a=rtpmap:98 H264/90000
a=fmtp:98 packetization-mode=1;profile-level-id=42e01f
a=rtpmap:99 VP8/90000
a=fmtp:99 max-fs=3600
a=rtpmap:100 H265/90000
a=fmtp:100 profile-id=1
a=sendonly
a=rtcp-rsize
a=ssrc:4012002156 cname:sip:test@test.tutpro.com
a=mid:1
a=framerate:30.00
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=content:main
a=label:2

stream: update 'audio'
stream: update 'video'
audio: Set audio decoder: AMR-WB 16000Hz 1ch
09:44:23.199#
TCP 192.168.243.45:5060 -> 192.168.243.45:47834
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.243.45:47834;received=192.168.243.45;branch=z9hG4bK20532738bbbd92b3;rport=47834
To: <sip:jh@test.tutpro.com>;tag=1f8b9d4cb834cba0
From: "Test Account" <sip:test@test.tutpro.com>;tag=2ed65afad3ac72b2
Call-ID: bb34024e3d14921e
CSeq: 3306 INVITE
Server: baresip v3.7.0 (x86_64/Linux)
Contact: <sip:jh@test.tutpro.com;gr=urn:uuid:9b21c1a8-dc58-a3d6-83d5-7be67cbe70ce>
Content-Type: application/sdp
Content-Length: 423

v=0
o=- 499068896 1875437093 IN IP4 192.168.243.45
s=-
c=IN IP4 192.168.243.45
t=0 0
m=audio 16126 RTP/AVP 98 99 0 8 101 9
a=rtpmap:98 AMR-WB/16000
a=rtpmap:99 AMR/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=rtpmap:9 G722/8000
a=recvonly
a=ssrc:3739447691 cname:sip:jh@test.tutpro.com
a=minptime:20
a=ptime:20
a=label:1
a=mid:0
m=video 0 RTP/AVP 0

test@test.tutpro.com: Call answered: sip:jh@test.tutpro.com
stream: update 'audio'
stream: update 'video'
audio: Set audio decoder: AMR-WB 16000Hz 1ch
[0:01:22] audio=0/0 video=0/0 (bit/s) efps=0.0/0.0    09:44:58.622#
TCP 192.168.243.45:5060 -> 192.168.243.45:47834
BYE sip:test-0x556e0e230010@192.168.243.45:47834;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 192.168.243.45;branch=z9hG4bK1117.a43bff2297a48f0f990387bd5e0a61f9.0;i=3
Via: SIP/2.0/TCP 192.168.243.45:47822;received=192.168.243.45;branch=z9hG4bK23d8b404a7fc3d98;rport=47822
Max-Forwards: 69
To: "Test Account" <sip:test@test.tutpro.com>;tag=2ed65afad3ac72b2
From: <sip:jh@test.tutpro.com>;tag=1f8b9d4cb834cba0
Call-ID: bb34024e3d14921e
CSeq: 19650 BYE
User-Agent: baresip v3.7.0 (x86_64/Linux)
X-RTP-Stat: EX=BareSip;CS=0;CD=82;PR=1191;PS=1195;PL=0,0;PD=0,0;JI=32.9,42.9;IP=0.0.0.0:16126,192.168.243.45:37312;EN=AMR-WB/16000;DE=AMR-WB/16000
Content-Length: 0


09:44:58.622#
TCP 192.168.243.45:47834 -> 192.168.243.45:5060
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.243.45;branch=z9hG4bK1117.a43bff2297a48f0f990387bd5e0a61f9.0;i=3
Via: SIP/2.0/TCP 192.168.243.45:47822;received=192.168.243.45;branch=z9hG4bK23d8b404a7fc3d98;rport=47822
To: "Test Account" <sip:test@test.tutpro.com>;tag=2ed65afad3ac72b2
From: <sip:jh@test.tutpro.com>;tag=1f8b9d4cb834cba0
Call-ID: bb34024e3d14921e
CSeq: 19650 BYE
Server: baresip v3.7.0 (x86_64/Linux)
X-RTP-Stat: EX=BareSip;CS=3000;CD=82;PR=1195;PS=1191;PL=0,0;PD=0,0;JI=42.9,32.9;IP=0.0.0.0:37312,192.168.243.45:16126;EN=AMR-WB/16000;DE=AMR-WB/16000
Content-Length: 0

```
It may matter if caller or callee is giving x.

**Comment by alfredh** [comment] 2023-12-09 11:34
thanks for testing.

Should we go ahead and merge the PR ?

**Comment by juha-h** [comment] 2023-12-09 23:01
As I wrote in above, the re pr that I tested broke the re-invite. Perhaps it has nothing to do with this baresip pr.

**Comment by maximilianfridrich** [comment] 2023-12-10 11:18
Thank you @juha-h! I have converted the re PR to a draft, I don't think it should be merged then. I have looked into the ACK problem in the past and it was quite mysterious. I will look into it again.

**Comment by maximilianfridrich** [comment] 2023-12-11 13:09
Great news! I finally found the ACK issue! The re PR is up to date and ready for review again.

This should resolve this issue and also finally #2114.

I have tested it with the test accounts that @juha-h provided us - thank you!

**Closed** 2023-12-19 10:33 UTC
