### ISSUE TITLE
Long-ish pulse device name is not accepted -- error shows last character was dropped

### ISSUE THREAD

**Issue by morciej** [baresip/baresip#1404] opened 2021-04-27 07:57 UTC
My setup is `Linux Mint Ulyssa/Focal 0.6.1-1build4` as per current repositories.

In .baresip/config, I have:
```
[...]
audio_player		pulse,alsa_output.pci-0000_00_1b.0.analog-stereo
audio_source	        pulse,alsa_input.usb-Logitech_Logitech_USB_Microphone-00.mono-fallback
audio_alert		pulse,alsa_output.pci-0000_00_1b.0.analog-stereo
[...]
```
This would work, but the middle line causes error that says:
```
pulse: could not connect to server (No such entity)
audio: start_source failed (pulse.alsa_input.usb-Logitech_Logitech_USB_Microphone-00.mono-fallbac): No such device
```
Notice that the last "k" was dropped in the device name.

I fall back to using just "pulse" for default, but it would be nice to be able to choose this particular mike.

Please kindly look into why it happens. Bug?

**Comment by sreimers** [comment] 2021-04-27 08:39
Can you test the latest stable release (0.6.1 is quite outdated):

- Remove all libre/baresip deb packages
- Follow these instructions: https://github.com/baresip/baresip/wiki/Install:-Stable-Release

**Comment by morciej** [comment] 2021-04-27 19:48
I downloaded the "latest" release. It installs correctly. I set `export LD_LIBRARY_PATH=/usr/local/lib`, but I am missing modules `pulse.so`, `g722.so`, `gsm.so` to have a working setup. Where can I get them?

**Comment by mbattista** [comment] 2021-04-27 22:02
Can you check your `.baresip/config` file if the module path is `/usr/local/lib/baresip/modules`?
 
If not, does the it work, if you change the module_path value to `/usr/local/lib/baresip/modules`?

**Comment by morciej** [comment] 2021-04-28 03:47
Yes, it does point there. I only have these modules in `/usr/local/lib/baresip/modules`:
```
account.so
aubridge.so
aufile.so
auloop.so
ausine.so
b2bua.so
cairo.so
cons.so
contact.so
ctrl_dbus.so
ctrl_tcp.so
debug_cmd.so
ebuacip.so
echo.so
evdev.so
fakevideo.so
g711.so
gtk.so
httpd.so
httpreq.so
ice.so
l16.so
menu.so
mixausrc.so
multicast.so
mwi.so
natpmp.so
oss.so
presence.so
rtcpsummary.so
selfview.so
serreg.so
snapshot.so
srtp.so
stdio.so
stun.so
syslog.so
turn.so
uuid.so
v4l2_codec.so
v4l2.so
vidbridge.so
vidinfo.so
vidloop.so
vumeter.so
x11grab.so
x11.so
```

**Comment by alfredh** [comment] 2021-04-28 17:15
you can try this:

```
make USE_PULSE=yes
```

**Comment by morciej** [comment] 2021-04-28 18:53
I get:
```
Package libpulse-simple was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpulse-simple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpulse-simple' found
  CC [M]  build-x86_64/modules/pulse/pulse.o
modules/pulse/pulse.c:7:10: fatal error: pulse/pulseaudio.h: No such file or directory
    7 | #include <pulse/pulseaudio.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [mk/mod.mk:49: build-x86_64/modules/pulse/pulse.o] Error 1
```

**Comment by sreimers** [comment] 2021-04-29 10:58
You need to install "libpulse-dev" package for pulseaudio and "libspandsp-dev" for g722

**Comment by alfredh** [comment] 2021-05-01 08:54
here is the code in baresip.h:

```c
/** Audio */
struct config_audio {
	char audio_path[256];   /**< Audio file directory           */
	char src_mod[16];       /**< Audio source module            */
	char src_dev[128];      /**< Audio source device            */
	char play_mod[16];      /**< Audio playback module          */
	char play_dev[128];     /**< Audio playback device          */
	char alert_mod[16];     /**< Audio alert module             */
	char alert_dev[128];    /**< Audio alert device             */
	uint32_t srate_play;    /**< Opt. sampling rate for player  */
	uint32_t srate_src;     /**< Opt. sampling rate for source  */
	uint32_t channels_play; /**< Opt. channels for player       */
	uint32_t channels_src;  /**< Opt. channels for source       */
	enum audio_mode txmode; /**< Audio transmit mode            */
	bool level;             /**< Enable audio level indication  */
	int src_fmt;            /**< Audio source sample format     */
	int play_fmt;           /**< Audio playback sample format   */
	int enc_fmt;            /**< Audio encoder sample format    */
	int dec_fmt;            /**< Audio decoder sample format    */
	struct range buffer;    /**< Audio receive buffer in [ms]   */
};
```

the maximum length of a device name is 127 characters ...

**Comment by alfredh** [comment] 2021-05-03 11:59
hi @morciej 

did you manage to compile the code as explained ?

**Comment by alfredh** [comment] 2021-05-06 09:13
the configuration should work as intended, I will close this for now.

please re-open if it does not work with master.

**Closed by alfredh** 2021-05-06 09:13 UTC

**Comment by morciej** [comment] 2023-02-20 02:28
Sorry, no, I gave up. It's not a developer computer, and I need a working phone on it, so enough experimenting. I set up Zoiper, and I am happy with it.
