### ISSUE TITLE
Dialing an extension directly via command line argument is not working without domain

### ISSUE THREAD

**Issue by capncybo** [baresip/baresip#1409] opened 2021-04-28 20:00 UTC
Since baresip_v1.1.0
Not working =  baresip -e d771
But this works = baresip -e d771@192.168.1.1

While on baresip_v1.0.0 (and earlier...)
baresip -e d771
Just worked

**Comment by cspiel1** [comment] 2021-04-30 06:43
Will have a look on this today.

**Comment by cspiel1** [comment] 2021-04-30 08:45
What is your setup and your accounts file?
Do you have a SIP proxy at 192.168.1.1?

Dialing through a SIP proxy on startup of baresip can't work. The registration has to be done first.

**Comment by capncybo** [comment] 2021-04-30 12:52
Thank you Christian for looking at this.
It's mostly raspberry Pi based cameras +
I am using an Asterisk 16 Server running at 192.168.1.1 via Entware/Asus
Router & USB-drive
It's configured to support conference calls so (more than one sip user/peer
can look at each camera) at the same time.

Many of the recent changes made to v1.1.0 undid all my previous efforts,
Until I found...
call_hold_other_calls   no      #Changed value because (Default: yes)
brakes multiple video-call support
(Thankfully you guys realised ONE-CALL is NOT-4-ALL  Lol but seriously,
thank you for adding the options to revert previous behaviour)

I thought baresip supports multiple instances so technically...
Baresip can already be registered + on a secondary launch can't it dial
multiple numbers on launch?
ex) baresip -e d771 -e d772 -e d773
(That used to work before v1.1.0)

One of my, accounts files:
***@***.***
;transport=tcp>;answermode=auto;auth_user=user8;auth_pass=passwordhere;regint=360


Thanks again for looking at this

**Comment by alfredh** [comment] 2021-05-01 09:23
can you test this patch:

```diff
diff --git a/src/uag.c b/src/uag.c
index d21d177..4273e5b 100644
--- a/src/uag.c
+++ b/src/uag.c
@@ -963,6 +963,10 @@ struct ua *uag_find_requri(const char *requri)
        if (!uag.ual.head)
                return NULL;
 
+       /* if there is only one UA, use that one */
+       if (uag.ual.head == uag.ual.tail)
+               return uag.ual.head->data;
+
        mb = mbuf_alloc(16);
        if (!mb)
                return NULL;
```

**Comment by capncybo** [comment] 2021-05-01 12:41
I just realised in my version of src... I didn't even have the uag.c file.
I'll try to test...

**Comment by capncybo** [comment] 2021-05-01 13:48
No luck but I'm not 100% sure I did things right.  After realizing I was
completely missing that file I added it to my existing baresip1.1.0/src
directory & manually made the changes via cut & paste.  I did a:
make -B
sudo make install
ldconfig

The following still fails: baresip -e d771
This still works: baresip -e ***@***.***

Note: before trying the above method...
I tried to build a current version of baresip with my most recent versions
of RE & REM.

I used:
git clone  (current code)

But after running
make
Got many build errors so.... I did the previous

**Comment by alfredh** [comment] 2021-05-01 14:09
can you try this:

```bash
cd src
git clone https://github.com/baresip/re
git clone https://github.com/baresip/rem
git clone https://github.com/baresip/baresip
sudo make install -C re
sudo make install -C rem
sudo ldconfig

cd baresip
make
```


if this does not work, please report the errors.

**Comment by capncybo** [comment] 2021-05-01 15:03
Thank you for the excellent instructions for building from live code.
They made the building sooooo simple.

However in my case... the outcome is still the same.
The following still fails: baresip -e d771
This still works: baresip -e ***@***.***

Regardless I do, Thank you for looking into this matter.

**Comment by cspiel1** [comment] 2021-05-03 05:59
As I told already, the problem is that at startup the registration was not done. It takes some time.

The UA is not selected because it is not registered at startup. You can force to use it by specifying the index of the UA:

E.g. I have to accounts
```
"A" <sip:a@localhost>;regint=0
"alice" <sip:alice@my-proxy.org>;regint=30;auth_pass=xyx
```

Start baresip with:
```
baresip -e d"771 1"
```

**Comment by alfredh** [comment] 2021-05-03 12:01
thanks for the explanation @cspiel1 

I will close this ticket as not-a-bug

**Closed by alfredh** 2021-05-03 12:01 UTC

**Comment by capncybo** [comment] 2021-05-03 15:38
Thanks for the added information.
Unfortunately I did not fully understand what you were trying to say, until
you gave the example above.
Appreciated,

T.
