### ISSUE TITLE
session closed: Function not implemented [38]

### ISSUE THREAD

**Issue by pergolafabio** [baresip/baresip#2342] opened 2022-11-21 19:19 UTC
Hey Guys, i have a verry simple setup to start, in my accounts i have setup an linphone account 

`<sip:user1@sip.linphone.org>;transport=tls;auth_pass=xxx
`
Configured rtsp with avformat...
When i dial user2@sip.linphone.org, i get error below....

`sip:user2@sip.linphone.org: session closed: Function not implemented [38]`
I see video in early media, i can answer, but then the video is gone

full log ( non working setup 7001 to 6001):
```

call: connecting to 'sip:user2@sip.linphone.org'..
call id: 886c4f52e8410937
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 110 Push sent (/)
video: stopping video source ..
video: stopping video display ..
aubridge: created device 'nil'
call: SIP Progress: 183 Session progress (application/sdp)
call: stream start (active=0)
stream: audio: enable RTP from remote
stream: video: enable RTP from remote
user1@sip.linphone.org: Call in-progress: sip:user2@sip.linphone.org
call: got SDP answer (475 bytes)
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 51.255.123.123:60297
stream: update 'video'
stream: video: starting RTCP with remote 51.255.123.123:16931
audio: update
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
audio: create auplay buffer [20 - 160 ms] [320 - 2560 bytes]
aubridge: created device 'nil'
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
audio: source started with sample format S16LE
audio tx pipeline:    aubridge ---> aubuf ---> auconv ---> auresamp ---> PCMU
audio rx pipeline:    aubridge <--- aubuf <--- auconv <--- auresamp <--- PCMU
video: update
Set video encoder: H264 packetization-mode=1 (1000000 bit/s, 30.00 fps)
avcodec: h264 encoder activated
avcodec: video encoder H264: 30.00 fps, 1000000 bit/s, pktsize=1280
video: start source
avformat: video: alloc dev='rtsp://admin:XXX@192.168.0.70:554/Streaming/Channels/102'
aubridge: thread start: 8000 Hz, 1 channels, format=S16LE
auresam: resample encoder 8000/1 --> 8000/1
[rtsp @ 0x55edc2c6d840] Missing PPS in sprop-parameter-sets, ignoring
avformat: 'video' using decoder 'h264' (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 1)
avformat: 'audio' using decoder 'pcm_mulaw' (PCM mu-law / G.711 mu-law)
video: stopping video display ..
[NULL @ 0x55edc2c72300] non-existing PPS 0 referenced
no video pts
stream: incoming rtp for 'audio' established, receiving from 51.255.123.123:60296
auresam: resample decoder 8000/1 --> 8000/10.0/0.0
call: got SDP answer (475 bytes)it/s) efps=0.0/0.0
user1@sip.linphone.org: Call answered: sip:user2@sip.linphone.org
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 51.255.123.123:60297
stream: update 'video'
stream: video: starting RTCP with remote 51.255.123.123:16931
audio: update
video: update
video: stopping video display ..
sip:user2@sip.linphone.org: session closed: Function not implemented [38]
video: stopping video source ..
video: stopping video display ..
video: stopping video source ..
video: stopping video display ..
audio: destroyed (started=0)
```

when i do the same test, but then with accouns registered on asterisk, when i do the test call from 7001 to 6001 , it works
see full log below, i can see early media AND i still see video after i pickup

when i do the same test, but then with accouns registered on asterisk, when i do the test call from 7001 to 6001 , it works
see full log below, i can see early media AND i still see video after i pickup

Whats wrong with the linphone setup ?

full log ( non working setup 7001 to 6001)

```

call uri: sip:6001@192.168.0.17
call: alloc with params laddr=192.168.0.17, af=AF_INET, use_rtp=1
call: use_video=1
call: connecting to 'sip:6001@192.168.0.17'..
call id: 1322d91bd31b2376
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 183 Session Progress (application/sdp)
call: stream start (active=0)
stream: audio: enable RTP from remote
stream: video: enable RTP from remote
7001@192.168.0.17: Call in-progress: sip:6001@192.168.0.17
call: got SDP answer (378 bytes)
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 192.168.0.17:14167
stream: update 'video'
stream: video: starting RTCP with remote 192.168.0.17:10817
audio: update
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
audio: create auplay buffer [20 - 160 ms] [320 - 2560 bytes]
aubridge: created device 'nil'
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
audio: source started with sample format S16LE
audio tx pipeline:    aubridge ---> aubuf ---> auconv ---> auresamp ---> PCMU
audio rx pipeline:    aubridge <--- aubuf <--- auconv <--- auresamp <--- PCMU
video: update
Set video encoder: H264 packetization-mode=0 (1000000 bit/s, 30.00 fps)
avcodec: h264 encoder activated
avcodec: video encoder H264: 30.00 fps, 1000000 bit/s, pktsize=1280
video: start source
avformat: video: alloc dev='rtsp://admin:XXXXX@192.168.0.70:554/Streaming/Channels/102'
aubridge: thread start: 8000 Hz, 1 channels, format=S16LE
auresam: resample encoder 8000/1 --> 8000/1
[rtsp @ 0x55c3ec409940] Missing PPS in sprop-parameter-sets, ignoring
avformat: 'video' using decoder 'h264' (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
avformat: 'audio' using decoder 'pcm_mulaw' (PCM mu-law / G.711 mu-law)
video: stopping video display ..
stream: incoming rtp for 'audio' established, receiving from 192.168.0.17:14166
no video pts
auresam: resample decoder 8000/1 --> 8000/10.0/0.0
call: got SDP answer (378 bytes)it/s) efps=0.0/0.0
7001@192.168.0.17: Call answered: sip:6001@192.168.0.17
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 192.168.0.17:14167
stream: update 'video'
stream: video: starting RTCP with remote 192.168.0.17:10817
audio: update
video: update
video: stopping video display ..
call: stream start (active=1)
audio: start
video: update
video: stopping video display ..
stream: audio: enable RTP from remote
stream: video: enable RTP from remote
7001@192.168.0.17: Call established: sip:6001@192.168.0.17
call: modify
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 192.168.0.17:14167
stream: update 'video'
stream: video: starting RTCP with remote 192.168.0.17:10817
audio: update
video: update
video: stopping video display ..
call: got SDP answer (378 bytes)
7001@192.168.0.17: Call answered: sip:6001@192.168.0.17
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 192.168.0.17:14167
stream: update 'video'
stream: video: starting RTCP with remote 192.168.0.17:10817
audio: update
video: update
video: stopping video display ..
sip:6001@192.168.0.17: session closed: Connection reset by peer [104]
video: stopping video source ..
video: stopping video display ..
sip:7001@192.168.0.17: Call with sip:6001@192.168.0.17 terminated (duration: 7 secs)
video: stopping video source ..
video: stopping video display ..
audio: destroyed (started=0)

```

**Comment by pergolafabio** [comment] 2022-11-22 12:29
ok, changed it:
`<sip:user1@sip.linphone.org;transport=tls>;auth_pass=xxx`

started with -v option, but doesnt give me more info ?

```
root@debian:/home/debian/baresip/build# ./baresip  -v
baresip v2.9.0 Copyright (C) 2010 - 2022 Alfred E. Heggestad et al.
Local network addresses:
     ens160:  192.168.0.240
     ens160:  fe80::20c:29ff:fe79:ac6a
uag: add local address 192.168.0.240
ua: adding SIP CA file: /etc/ssl/certs/ca-certificates.crt
ua: adding SIP CA path:
uag: add local address fe80::20c:29ff:fe79:ac6a
ui: stdio
cons: UI console listening on 0.0.0.0:5555
ui: cons
ui: http
httpd: listening on 0.0.0.0:8000
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: auconv
aufilt: auresamp
ausrc: aubridge
auplay: aubridge
vidcodec: H264
vidcodec: H264
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
ausrc: avformat
vidsrc: avformat
uuid: loaded UUID ab4f1010-7493-f699-6026-f68a25972326 from file /home/debian/.baresip/uuid
medianat: stun
medianat: turn
medianat: ice
module: loading app b2bua.so
b2bua: inbound UA not found
b2bua: module closing..
module b2bua.so: No such file or directory [2]
module: loading app account.so
ua: ua_register sip:user1@sip.linphone.org
Populated 1 account
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app netroam.so
Populated 2 audio codecs
Populated 2 audio filters
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
user1@sip.linphone.org: (prio 0) {0/TLS/v4} 200 Registration successful (Flexisip/2.2.0-3-g73237746 (sofia-sip-nta/2.0)) [1 binding]
All 1 useragent registered successfully! (140 ms)
>                     user2
user1@sip.linphone.org: selected for request
call uri: user2
call: alloc with params laddr=192.168.0.240, af=AF_INET, use_rtp=1
call: use_video=1
call: connecting to 'sip:user2@sip.linphone.org;transport=tls'..
call id: 3fd46d650899792c
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 110 Push sent (/)
video: stopping video source ..
video: stopping video display ..
play: /usr/local/share/baresip/ringback.wav: No such file or directory [2]
call: SIP Progress: 183 Session progress (application/sdp)
call: stream start (active=0)
stream: audio: enable RTP from remote
stream: video: enable RTP from remote
user1@sip.linphone.org: Call in-progress: sip:user2@sip.linphone.org;transport=tls
call: got SDP answer (375 bytes)
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 51.255.123.123:7533
stream: update 'video'
stream: video: starting RTCP with remote 51.255.123.123:50555
audio: update
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: start
audio: create auplay buffer [20 - 160 ms] [320 - 2560 bytes]
aubridge: created device 'nil'
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: start
audio: source started with sample format S16LE
audio tx pipeline:    aubridge ---> aubuf ---> auconv ---> auresamp ---> PCMU
audio rx pipeline:    aubridge <--- aubuf <--- auconv <--- auresamp <--- PCMU
video: update
Set video encoder: H264 packetization-mode=1 (1000000 bit/s, 30.00 fps)
avcodec: h264 encoder activated
avcodec: video encoder H264: 30.00 fps, 1000000 bit/s, pktsize=1280
video: start source
avformat: video: alloc dev='rtsp://admin:xxx@192.168.0.70:554/Streaming/Channels/102'
aubridge: thread start: 8000 Hz, 1 channels, format=S16LE
auresamp: resample encoder 8000/1 --> 8000/1
[rtsp @ 0x55f29bce7600] Missing PPS in sprop-parameter-sets, ignoring
avformat: 'video' using pass-through
avformat: 'audio' using decoder 'pcm_mulaw' (PCM mu-law / G.711 mu-law)
video: stopping video display ..
stream: incoming rtp for 'audio' established, receiving from 51.255.123.123:7532
no video pts
auresamp: resample decoder 8000/1 --> 8000/1.0/0.0
call: got SDP answer (375 bytes)o=416826/0 (bit/s) efps=0.0/0.0
user1@sip.linphone.org: Call answered: sip:user2@sip.linphone.org;transport=tls
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 51.255.123.123:7533
stream: update 'video'
stream: video: starting RTCP with remote 51.255.123.123:50555
audio: update
video: update
video: stopping video display ..
sip:user2@sip.linphone.org;transport=tls: session closed: Function not implemented [38]
video: stopping video source ..
video: stopping video display ..
video: stopping video source ..
video: stopping video display ..
audio: destroyed (started=0)
sa: sa_set_port: no af 0 (port 5223)
sa: sa_set_port: no af 0 (port 5223)

```

**Comment by pergolafabio** [comment] 2022-11-22 12:30
my issue is that it stops the video, i used avformat module with RTSP stream...
i only see the RTSP stream in early media, its gone after i pickup, it stops the video, as you can also see in log

**Comment by alfredh** [comment] 2022-11-23 12:38
duplicate of https://github.com/baresip/baresip/issues/2337

**Closed by alfredh** 2022-11-23 12:38 UTC
