### ISSUE TITLE
(Audio) Problem with the g722 codec - clipping and crackling

### ISSUE THREAD

**Issue by jaimet** [baresip/baresip#2164] opened 2022-09-28 13:44 UTC
Hi.

I have an audio quality problem when I use the g722 codec that I do not have when I use the g711 codec. It's easy to reproduce:

Make sure that only g722.so is permitted in config/"Audio codec Modules", then call thetestcall@opensips.org. After the intro message ("This is 722"), I press "#" to get to the main menu, then "4" for "music on hold". The sound is bad quality - I think it is clipping.

Now for the control: make sure that only g711.so is permitted in config/"Audio codec Modules", then again call thetestcall@opensips.org. After the intro message ("This is u-law"), I press "#" to get to the main menu, then "4" for "music on hold". The sound is better quality with no clipping.

(FWIW, I am actually here following a suggestion from [Juha Heinanen](https://github.com/juha-h/baresip-studio/issues/289))

TIA, Jaime

**Comment by cspiel1** [comment] 2022-09-28 13:56
This is a cool test! Thanks!
I am able to reproduce this. Will have a look on this in the next days.

**Comment by cspiel1** [comment] 2022-09-28 14:04
Yes it is clipping. I could verify this in audacity. With the module `sndfile` encode/decode streams can be recorded to WAV files.
I guess that the peer (`opensips.org`) already sends clipped G722 stream. But this can be verified by "manually" decoding the RTP stream from a PCAP.
Wireshark is able to do this.
- Tomorrow I will talk to our audio experts.
- We could also try other SIP phones.

**Comment by cspiel1** [comment] 2022-09-28 14:09
The PCAP tells that the remote is a:
```
Server: Asterisk PBX 19.6.0
```

**Comment by juha-h** [comment] 2022-09-28 14:14
Christian Spielberger writes:

> Yes it is clipping. I could verify this in audacity. With the module
> `sndfile` encode/decode streams can be recorded to WAV files. 
> I guess that the peer (`opensips.org`) already sends clipped G722 stream. But this can be verified by "manually" decoding the RTP stream from a PCAP.
> Wireshark is able to do this.
> - Tomorrow I will talk to our audio experts.
> - We could also try other SIP phones.

I too was able to reproduce this with baresip.  There is no clipping or
crackling when I call ***@***.*** from Linphone using g722.

**Comment by cspiel1** [comment] 2022-09-28 14:35
I have a util program that uses libpcap to extract the pcm raw data from the G722 stream. This can be loaded into audacity. There  is no clipping in the incoming audio stream. This points to `spandsp` to be responsible for the clipping.
I will look to this closer tomorrow.

**Comment by sreimers** [comment] 2022-09-28 14:57
Maybe this is related: https://github.com/freeswitch/spandsp/commit/f5b7125d1a983a96558a8f8f7dcb3dd7b867343d

Looks like most distros have a old spandsp version, the last snapshot release (spandsp-20180108.tar.gz) contains the same freeswitch change. Maybe someone can verify if these upstream versions fixes the issue (can test later).

**Comment by sreimers** [comment] 2022-09-28 16:12
Linphone seems to have some up and down scaling by default:

https://github.com/BelledonneCommunications/mediastreamer2/commit/6ceb51f095c5f4f128a840752a9dd982ed7f2826

**Comment by juha-h** [comment] 2022-09-28 16:44
Sebastian Reimers writes:

> Looks like most distros have a old spandsp version, the last snapshot
> release (spandsp-20180108.tar.gz) contains the same freeswitch
> change. Maybe someone can verify if these upstream versions fixes the
> issue (can test later).

I applied
https://github.com/freeswitch/spandsp/commit/f5b7125d1a983a96558a8f8f7dcb3dd7b867343d
to my copy of spandsp source https://github.com/juha-h/spandsp (same as
what Debian has) and after that the cracklings are gone.

**Comment by sreimers** [comment] 2022-09-28 18:32
I think the upstream patch is the best solution. Rescaling is only a workaround and needs support on both sides. Unsure about what we can do, other than document the problem and hope there is a patched spandsp release some day. For voice calls the effect should be limited.

**Comment by juha-h** [comment] 2022-09-28 18:49
I agree. So the solution is to make sure that patch

https://github.com/freeswitch/spandsp/commit/f5b7125d1a983a96558a8f8f7dcb3dd7b867343d

has been applied to the used libspandsp.

I think we could close this now, since the bug is not in baresip g722
module.

**Comment by cspiel1** [comment] 2022-09-29 05:00
Thanks! We will also apply this patch to our products.

**Closed by cspiel1** 2022-09-29 05:00 UTC
