### ISSUE TITLE
SIP Register "404 Not Found" - change Contact URI User Part?

### ISSUE THREAD

**Issue by mani9876** [baresip/baresip#1131] opened 2020-11-25 16:13 UTC
Hello,

I am using baresip on a Raspberry Pi, I would like to connect it to my PBX (Siemens Hipath 4000), but my PBX always answeres the Register messages with "404 Not Found" I think it's because the Contact URI User Part is <extension#-ID> (e.g. 140-0x10be123@192.168.10.10)
Is it possible to alter that field, so that the contact URI only is extension#@domain e.g. 140@192.168.10.10?

Connection to a FritzBox or Hipath 3000 works fine, only connecting to the Hipath 4000 makes some problems.

Thank you!
Best regards
Manuel

EDIT:
I've made a test, I took the original Packet sent from Baresip, altered the contact URI to 140@192.168.10.10 and send it again (with a Packet sender) to my SIP registrar, and I get a 200 OK back. So it's definitely a problem with the Contact URI User Part, is there a reason why baresip sends an ID, and not only the extension# as all the other SIP clients does?

**Comment by alfredh** [comment] 2020-11-28 13:22
it is probably better if you use the mailing list for these kind of questions, see:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

you should also include the full SIP trace, full baresip log and config files.
this is most likely a bug in Siemens Hipath.

**Comment by mani9876** [comment] 2020-11-29 20:21
Hello Alfred,

sorry, I've added all the necessary logs, and traces. 
[baresip.zip](https://github.com/baresip/baresip/files/5612794/baresip.zip)

accounts: Baresip accounts file
baresip.log: Log file, starting baresip
baresip.pcap: SIP Trace between baresip and PBX
spoofed.pcap: SIP Trace of spoofed Register packet, I took the baresip Register Packet, spoofed the Contact User Part and the IP Address (as I have sent the packet from another Computer)

Am I right, that in the SIP specification, the "from" header has to be taken into account for the PBX, and not the contact header?

I am also going to contact Siemens (Unify), but I am very confused, we have several customers, where we are servicing the Hipath 4000, and we were never facing any problems, regarding SIP Clients, because none of SIP Clients have a different User in the contact Header, than the Extension Number.
I am also convinced that Unify will not change the behavior of their PABX :(.

Do you think it's possible to add a parameter to baresip, to overcome that problem, so that the contact user is only the Extension # without any ID?

Thanks
Best regards
Manuel

**Comment by alfredh** [comment] 2020-12-12 09:38
baresip is following the SIP specification, and it is also compliant with many SIP servers.

You should report this problem first to Siemens and ask them why they dont handle a
contact user of format "username-0x12345678@domain.com".

Here is the code:
https://github.com/baresip/baresip/blob/master/src/ua.c#L777

if baresip has multiple accounts, we need to be able to separate incoming requests
so it goes to the right useragent.

I am going to close this, as it is not a bug in baresip.

**Closed by alfredh** 2020-12-12 09:38 UTC
