### ISSUE TITLE
 ICE and ZRTP don't work (#1087) 

### ISSUE THREAD

**Issue by samwell-ho** [baresip/baresip#1596] opened 2021-09-09 10:08 UTC
It's old issue (([#1087](https://github.com/baresip/baresip/issues/1087)) 

Now I update some my softwares:
- Baresip v1.0.0 from https://github.com/baresip/baresip.
- re v2.0.1 from https://github.com/baresip/re
- rem v1.0.0  from https://github.com/creytiv/rem
- libzrtp from https://github.com/juha-h/libzrtp
- SIP server: Kamailio 5.5.1

The test topo is as follows:

Baresip-01 <--> NAT --> Internet <--> Kamailio 5.5.1 <--> Intenet <--> NAT <--> Baresip-02

SIP account config for Baresip-01:
```
<sip:101@210.245.59.74:30002;transport=tls>;auth_pass=very_long_password;video_codecs=h264,vp9;regint=300;medianat=ice;stunserver=stun:stun4.l.google.com:19302;
```

SIP account config for Baresip-02:
```
<sip:102@210.245.59.74:30002;transport=tls>;auth_pass=very_long_password;video_codecs=h264,vp9;regint=300;medianat=ice;stunserver=stun:stun4.l.google.com:19302;
```

Two baresip config files are the same as follows:
```
#
# baresip configuration
#

#------------------------------------------------------------------------------
log_level    		debug    # debug, info, warning

# Core
poll_method		epoll		# poll, select, epoll ..

# SIP
#sip_listen		120.72.122.14:5060
sip_certificate		/etc/baresip/keys/host.pem
sip_cafile		/etc/baresip/keys/ca.crt

# Call
call_local_timeout	65
call_max_calls		1

# Audio
audio_path		/usr/share/baresip
audio_player		alsa,mix_stream
audio_source		alsa,plughw:0,0
audio_alert		alsa,mix_stream
ausrc_srate		48000
auplay_srate		48000
#ausrc_channels		0
auplay_channels		2
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..

# Video
video_source		v4l2,/dev/video1
video_display		qtupload,nil
video_size		320x240
#video_size              640x480
#video_size              768x576
#video_size              1280x800
video_bitrate		256000
video_fps		25
video_fullscreen	yes
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		21100-21999
rtp_bandwidth		1024-2048 # [kbit/s]
rtcp_mux		        yes
jitter_buffer_delay	5-10		# frames
rtp_stats		        yes
rtp_timeout		120
rtcp_enable		yes

# Network
net_prefer_ipv6		no
dns_server		8.8.8.8:53
#net_interface		eth0

# BFCP
#bfcp_proto		udp

#------------------------------------------------------------------------------
# Modules

module_path		/usr/lib/baresip/modules

# UI Modules
module			stdio.so
#module			cons.so
#module			evdev.so
module			httpd.so

# Audio codec Modules (in order)
#module			opus.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
module			g711.so
#module			gsm.so
#module			l16.so
#module			bv32.so
#module			mpa.so
#module			codec2.so
#module			ilbc.so
#module			isac.so

# Audio filter Modules (in encoding order)
#module			vumeter.so
#module			sndfile.so
#module			speex_aec.so
#module			speex_pp.so
#module			plc.so
#module			webrtc_aec.so

# Audio driver Modules
module			alsa.so
#module			pulse.so
#module			jack.so
#module			portaudio.so
#module			aubridge.so
#module			aufile.so

# Video codec Modules (in order)
module			avcodec.so
#module			vp8.so
module			vp9.so
#module			h265.so

# Video filter Modules (in encoding order)
module			selfview.so
#module			snapshot.so
#module			swscale.so
#module			vidinfo.so

# Video source modules
module			v4l2.so
#module			v4l2_codec.so
#module			avformat.so
#module			x11grab.so
#module			cairo.so
#module			vidbridge.so

# Video display modules
#module			directfb.so
#module			x11.so
#module			sdl2.so
#module			fakevideo.so
#module			opengles.so

# Audio/Video source modules
#module			rst.so
#module			gst1.so
#module			gst_video1.so

# Media NAT modules
module			stun.so
module			turn.so
module			ice.so
#module			natpmp.so
module			pcp.so

# Media encryption modules
module			srtp.so
#module			dtls_srtp.so
module			zrtp.so


#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp		uuid.so
module_tmp		account.so


#------------------------------------------------------------------------------
# Application Modules

module_app		auloop.so
#module_app		b2bua.so
module_app		contact.so
module_app		debug_cmd.so
#module_app		dtmfio.so
#module_app		echo.so
#module_app		gtk.so
module_app		menu.so
#module_app		mwi.so
#module_app		presence.so
#module_app		syslog.so
#module_app		mqtt.so
#module_app		ctrl_tcp.so
module_app		vidloop.so


#------------------------------------------------------------------------------
# Module parameters


# UI Modules parameters
cons_listen		0.0.0.0:5555 # cons

http_listen		0.0.0.0:8000 # httpd - server

ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp

evdev_device		/dev/input/event1

# Opus codec parameters
opus_bitrate		28000 # 6000-510000
#opus_stereo		yes
#opus_sprop_stereo	yes
#opus_cbr		no
#opus_inbandfec		no
#opus_dtx		no
#opus_mirror		no
#opus_complexity	10
#opus_application	audio	# {voip,audio}
#opus_samplerate	48000

# Opus Multistream codec parameters
#opus_ms_channels	2	#total channels (2 or 4)
#opus_ms_streams		2	#number of streams
#opus_ms_c_streams	2	#number of coupled streams

vumeter_stderr		yes

# Selfview
video_selfview		window # {window,pip}
selfview_size		64x64

# ICE
ice_turn		       no
ice_debug		yes
ice_nomination       regular #aggressive #regular	# {regular,aggressive}
ice_mode		full	# {full,lite}

# ZRTP
#zrtp_hash		no  # Disable SDP zrtp-hash (not recommended)

# Menu
#menu_bell		yes
#redial_attempts	0 # Num or <inf>
#redial_delay		5 # Delay in seconds
#ringback_disabled	no
#statmode_default	off

# avcodec
avcodec_h264enc	libx264
avcodec_h264dec	h264

# h265
#h265_encoder		libx265
#h265_decoder		hevc

codec2_mode		0
```

When calling between two devices, the key negotiation step under ZRTP can be done, but the media stream cannot be sent.

Debug on baresip-01:

```
Local network address:  IPv4=eth0|192.168.1.110

ui: stdio
ui: http
httpd: listening on 0.0.0.0:8000
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidcodec: VP9
vidfilt: selfview_window
vidsrc: v4l2
medianat: stun
medianat: turn
medianat: ice
pcp: using PCP server at 192.168.1.1:5351
medianat: pcp
mediaenc: zrtp
uuid: loaded UUID f8494976-5329-59b7-e996-3386a776350d from file uuid
using stunserver: 'stun:stun4.l.google.com:19302'
886001@210.245.59.74: Using medianat 'ice'
886001@210.245.59.74: Using media encryption 'zrtp'
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 38 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 0 audio filters
Populated 6 video codecs
Populated 1 video filter
megasip is ready.
101@210.245.59.74: {0/TLS/v4} 200 OK (kamailio (5.5.1 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (300 ms)

>                           886002
call: alloc with params laddr=192.168.1.110, af=AF_INET, use_rtp=1
ice: new session with STUN-server at stun4.l.google.com (username=886001)
stream: audio: starting mediaenc 'zrtp' (wait_secure=0)
call: use_video=1
stream: video: starting mediaenc 'zrtp' (wait_secure=0)
call: connecting to 'sip:102@210.245.59.74:30002;transport=tls'..
ice: resolved STUN-server to address 173.194.200.127:19302
audio: added interface: eth0:192.168.1.110 (local prio 0)
ice: gathering srflx for comp 1 ..
video: added interface: eth0:192.168.1.110 (local prio 0)
ice: gathering srflx for comp 1 ..
ice: srflx gathering for comp 1 complete.
ice: all components gathered.
video: comp1 setting local: 118.70.156.15:59346
ice: video: Default local candidates: 118.70.156.15:59346 / ?
ice: srflx gathering for comp 1 complete.
ice: all components gathered.
audio: comp1 setting local: 118.70.156.15:37416
ice: audio: Default local candidates: 118.70.156.15:37416 / ?
call: media-nat 'ice' established/gathered
call: SIP Progress: 100 trying -- your call is important to us (/)
call: SIP Progress: 180 Ringing (/)
video: stopping video source ..
alsa: reset: srate=8000, ch=1, num_frames=320, pcmfmt=S16_LE
alsa: playback started (mix_stream)
call: got SDP answer (1317 bytes)
call: update media
stream: update 'audio'
audio: RTP/RTCP multiplexing enabled
stream: update 'video'
video: RTP/RTCP multiplexing enabled
{      audio.1} Set default remote candidate: srflx:118.70.233.52:55160
{      video.1} Set default remote candidate: srflx:118.70.233.52:41554
{      audio. } starting connectivity checks with 2 candidate pairs
{      audio.1}  host <--->  host  FSM:      Frozen ===> Waiting
{      audio.1}  host <---> srflx  FSM:      Frozen ===> Waiting
{      video. } starting connectivity checks with 2 candidate pairs
call: stream start (active=1)
stream: Enable RTP timeout (120000 milliseconds)
stream: Enable RTP timeout (120000 milliseconds)
101@210.245.59.74: Call established: sip:102@210.245.59.74:30002;transport=tls
alsa: stopping playback thread (mix_stream)
{      audio.1}  host <--->  host  FSM:     Waiting ===> InProgress
{      video.1}  host <--->  host  FSM:      Frozen ===> InProgress
stream: last "audio" RTP packet: 375 milliseconds
check_rtp: not checking (dir=inactive)
stream: last "audio" RTP packet: 1375 milliseconds
check_rtp: not checking (dir=inactive)
stream: last "audio" RTP packet: 2375 milliseconds
check_rtp: not checking (dir=inactive)
{      audio.1}  host <--->  host  FSM:  InProgress ===> Failed
{      audio.1}  host <---> srflx  FSM:     Waiting ===> InProgress
{      video.1}  host <--->  host  FSM:  InProgress ===> Failed
{      video.1}  host <---> srflx  FSM:      Frozen ===> InProgress
{      audio.1} New local candidate for mapped 118.70.156.15:37416
{      audio.1}  host <---> srflx  FSM:  InProgress ===> Succeeded
ice: audio: connectivity check is complete (update=1)
audio: Dumping media state: ----- ICE Media <audio> -----
 local_mode=Full, remote_mode=Full, local_role=Controlling
 local_ufrag="tQwf0fI" local_pwd="cAoUN2uSz0zRgcD0GdgUhwb2LVF5B1I"
 Components: (1)
  id=1 ldef=118.70.156.15:37416 rdef=118.70.233.52:55160 concluded=1
 Local Candidates:  (2)
  {1} fnd=c0a8016e prio=7e0000ff eth0:host:192.168.1.110:23336
  {1} fnd=76469c0e prio=640000ff eth0:srflx:118.70.156.15:37416 (rel-addr=192.168.1.110:23336)
 Remote Candidates:  (2)
  {1} fnd=c0a80179 prio=7e0000ff host:192.168.1.121:6904
  {1} fnd=7646e935 prio=640000ff srflx:118.70.233.52:55160 (rel-addr=192.168.1.121:6904)
 Check list: [state=Completed] (1)
     {comp=1}     Failed {   } eth0:host:192.168.1.110:23336 <---> host:192.168.1.121:6904 (Connection timed out)
 Valid list:  (2)
  *  {comp=1}  Succeeded { VN} eth0:srflx:118.70.156.15:37416 <---> srflx:118.70.233.52:55160
     {comp=1}  Succeeded { V } eth0:host:192.168.1.110:23336 <---> srflx:118.70.233.52:55160
STUN debug:
STUN client transactions: (1)
 method=Binding tid=4871ae916fe60bad82edb81e rto=100ms tmr=100 n=1 interval=100

stream: mnat 'ice' connected: raddr 118.70.233.52:55160
stream: audio: starting RTCP with remote 118.70.233.52:55160
stream: audio: starting mediaenc 'zrtp' (wait_secure=0)
{      video.1} New local candidate for mapped 118.70.156.15:59346
{      video.1}  host <---> srflx  FSM:  InProgress ===> Succeeded
ice: video: connectivity check is complete (update=1)
video: Dumping media state: ----- ICE Media <video> -----
 local_mode=Full, remote_mode=Full, local_role=Controlling
 local_ufrag="tQwf0fI" local_pwd="cAoUN2uSz0zRgcD0GdgUhwb2LVF5B1I"
 Components: (1)
  id=1 ldef=118.70.156.15:59346 rdef=118.70.233.52:41554 concluded=1
 Local Candidates:  (2)
  {1} fnd=c0a8016e prio=7e0000ff eth0:host:192.168.1.110:12498
  {1} fnd=76469c0e prio=640000ff eth0:srflx:118.70.156.15:59346 (rel-addr=192.168.1.110:12498)
 Remote Candidates:  (2)
  {1} fnd=c0a80179 prio=7e0000ff host:192.168.1.121:26066
  {1} fnd=7646e935 prio=640000ff srflx:118.70.233.52:41554 (rel-addr=192.168.1.121:26066)
 Check list: [state=Completed] (1)
     {comp=1}     Failed {   } eth0:host:192.168.1.110:12498 <---> host:192.168.1.121:26066 (Connection timed out)
 Valid list:  (2)
  *  {comp=1}  Succeeded { VN} eth0:srflx:118.70.156.15:59346 <---> srflx:118.70.233.52:41554
     {comp=1}  Succeeded { V } eth0:host:192.168.1.110:12498 <---> srflx:118.70.233.52:41554
STUN debug:
STUN client transactions: (1)
 method=Binding tid=bd1e71ce072d0fa3d0d64c3b rto=100ms tmr=100 n=1 interval=100

stream: mnat 'ice' connected: raddr 118.70.233.52:41554
stream: video: starting RTCP with remote 118.70.233.52:41554
stream: video: starting mediaenc 'zrtp' (wait_secure=0)
stream: last "audio" RTP packet: 3420 milliseconds
check_rtp: not checking (dir=inactive)

Peer short term public key Y is valid.
[0:00:04] audio=0/0 video=0/0 (bit/s) efps=0.0/0.0
My   ZID:       0100000081e62034913e16ac
Peer ZID:       130000004ec0093fc0a3ea4b
Peer SAS1:      klaxon
zrtp: verify SAS <klaxon> <underfoot> for remote peer 130000004ec0093fc0a3ea4b (type /zrtp_verify 130000004ec0093fc0a3ea4b to verify)
call: mediaenc event 'Verify Request' (klaxon,underfoot,130000004ec0093fc0a3ea4b)
zrtp: got security_event '16' (bit/s) efps=0.0/0.0
stream: last "audio" RTP packet: 4420 milliseconds
check_rtp: not checking (dir=inactive)
stream: last "audio" RTP packet: 5420 milliseconds
check_rtp: not checking (dir=inactive)
stream: last "audio" RTP packet: 6421 milliseconds
check_rtp: not checking (dir=inactive)
stream: last "audio" RTP packet: 7421 milliseconds
...
...(No media packets sent or received)
...
```

Debug on baresip-02:

```
Local network address:  IPv4=eth0|192.168.1.121 

ui: stdio
ui: http
httpd: listening on 0.0.0.0:8000
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidcodec: VP9
vidfilt: selfview_window
vidsrc: v4l2
medianat: stun
medianat: turn
medianat: ice
pcp: using PCP server at 192.168.1.1:5351
medianat: pcp

mediaenc: zrtp
uuid: loaded UUID 40f0385f-2140-e3ef-3869-4cfa03703834 from file uuid
using stunserver: 'stun:stun4.l.google.com:19302'
102@210.245.59.74: Using medianat 'ice'
102@210.245.59.74: Using media encryption 'zrtp'
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 0 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 0 audio filters
Populated 6 video codecs
Populated 1 video filter
megasip is ready.
102@210.245.59.74: {0/TLS/v4} 200 OK (kamailio (5.5.1 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (304 ms)
ua: sipsess connect via TLS 210.245.59.74:30002 --> 192.168.1.121:54576
call: alloc with params laddr=192.168.1.121, af=AF_INET, use_rtp=1
ice: new session with STUN-server at stun4.l.google.com (username=886002)
stream: audio: starting mediaenc 'zrtp' (wait_secure=0)
call: use_video=1
stream: video: starting mediaenc 'zrtp' (wait_secure=0)
ice: resolved STUN-server to address 173.194.200.127:19302
audio: added interface: eth0:192.168.1.121 (local prio 0)
ice: gathering srflx for comp 1 ..
video: added interface: eth0:192.168.1.121 (local prio 0)
ice: gathering srflx for comp 1 ..
ice: srflx gathering for comp 1 complete.
ice: all components gathered.
audio: comp1 setting local: 118.70.233.52:55160
ice: audio: Default local candidates: 118.70.233.52:55160 / ?
ice: srflx gathering for comp 1 complete.
ice: all components gathered.
video: comp1 setting local: 118.70.233.52:41554
ice: video: Default local candidates: 118.70.233.52:41554 / ?
call: media-nat 'ice' established/gathered
sip:102@210.245.59.74:30002: Incoming call from:  sip:101@210.245.59.74:30002 - (press 'a' to accept)
alsa: reset: srate=44100, ch=2, num_frames=1764, pcmfmt=S16_LE
alsa: playback started (mix_stream)
sip:102@210.245.59.74:30002: Answering incoming call
alsa: stopping playback thread (mix_stream)
call: answering call on line 1 from sip:101@210.245.59.74:30002 with 200
call: update media
stream: update 'audio'
audio: RTP/RTCP multiplexing enabled
stream: update 'video'
video: RTP/RTCP multiplexing enabled
{      audio.1} Set default remote candidate: srflx:118.70.156.15:37416
{      video.1} Set default remote candidate: srflx:118.70.156.15:59346
{      audio. } starting connectivity checks with 2 candidate pairs
{      audio.1}  host <--->  host  FSM:      Frozen ===> Waiting   
{      audio.1}  host <---> srflx  FSM:      Frozen ===> Waiting   
{      video. } starting connectivity checks with 2 candidate pairs
[10;1000][11;1000]{      audio.1}  host <--->  host  FSM:     Waiting ===> InProgress
{      video.1}  host <--->  host  FSM:      Frozen ===> InProgress
call: stream start (active=1)
stream: Enable RTP timeout (120000 milliseconds)
stream: Enable RTP timeout (120000 milliseconds)
102@210.245.59.74: Call established: sip:101@210.245.59.74:30002
stream: last "audio" RTP packet: 10 milliseconds
check_rtp: not checking (dir=inactive)
stream: last "audio" RTP packet: 1010 milliseconds    
check_rtp: not checking (dir=inactive)
stream: last "audio" RTP packet: 2010 milliseconds    
check_rtp: not checking (dir=inactive)
{      audio.1}  host <--->  host  FSM:  InProgress ===> Failed    
{      audio.1}  host <---> srflx  FSM:     Waiting ===> InProgress
{      video.1}  host <--->  host  FSM:  InProgress ===> Failed    
{      video.1}  host <---> srflx  FSM:      Frozen ===> InProgress
{      audio.1} New local candidate for mapped 118.70.233.52:55160
{      audio.1}  host <---> srflx  FSM:  InProgress ===> Succeeded 
ice: audio: connectivity check is complete (update=0)
audio: Dumping media state: ----- ICE Media <audio> -----
 local_mode=Full, remote_mode=Full, local_role=Controlled
 local_ufrag="92AGyRF" local_pwd="pvgG5qT4Ovl6JIAkmWLC4E2vyZHaAQJ"
 Components: (1)
  id=1 ldef=118.70.233.52:55160 rdef=118.70.156.15:37416 concluded=1
 Local Candidates:  (2)
  {1} fnd=c0a80179 prio=7e0000ff eth0:host:192.168.1.121:6904
  {1} fnd=7646e935 prio=640000ff eth0:srflx:118.70.233.52:55160 (rel-addr=192.168.1.121:6904)
 Remote Candidates:  (2)
  {1} fnd=c0a8016e prio=7e0000ff host:192.168.1.110:23336
  {1} fnd=76469c0e prio=640000ff srflx:118.70.156.15:37416 (rel-addr=192.168.1.110:23336)
 Check list: [state=Completed] (1)
     {comp=1}     Failed {   } eth0:host:192.168.1.121:6904 <---> host:192.168.1.110:23336 (Connection timed out)
 Valid list:  (2)
  *  {comp=1}  Succeeded { VN} eth0:srflx:118.70.233.52:55160 <---> srflx:118.70.156.15:37416
     {comp=1}  Succeeded { V } eth0:host:192.168.1.121:6904 <---> srflx:118.70.156.15:37416
STUN debug:
STUN client transactions: (1)
 method=Binding tid=e9786d86f9e1a509b13338e3 rto=100ms tmr=99 n=1 interval=100

stream: mnat 'ice' connected: raddr 118.70.156.15:37416 
stream: audio: starting RTCP with remote 118.70.156.15:37416
stream: audio: starting mediaenc 'zrtp' (wait_secure=0)
{      video.1} New local candidate for mapped 118.70.233.52:41554
{      video.1}  host <---> srflx  FSM:  InProgress ===> Succeeded 
ice: video: connectivity check is complete (update=0)
video: Dumping media state: ----- ICE Media <video> -----
 local_mode=Full, remote_mode=Full, local_role=Controlled
 local_ufrag="92AGyRF" local_pwd="pvgG5qT4Ovl6JIAkmWLC4E2vyZHaAQJ"
 Components: (1)
  id=1 ldef=118.70.233.52:41554 rdef=118.70.156.15:59346 concluded=1
 Local Candidates:  (2)
  {1} fnd=c0a80179 prio=7e0000ff eth0:host:192.168.1.121:26066
  {1} fnd=7646e935 prio=640000ff eth0:srflx:118.70.233.52:41554 (rel-addr=192.168.1.121:26066)
 Remote Candidates:  (2)
  {1} fnd=c0a8016e prio=7e0000ff host:192.168.1.110:12498
  {1} fnd=76469c0e prio=640000ff srflx:118.70.156.15:59346 (rel-addr=192.168.1.110:12498)
 Check list: [state=Completed] (1)
     {comp=1}     Failed {   } eth0:host:192.168.1.121:26066 <---> host:192.168.1.110:12498 (Connection timed out)
 Valid list:  (2)
  *  {comp=1}  Succeeded { VN} eth0:srflx:118.70.233.52:41554 <---> srflx:118.70.156.15:59346
     {comp=1}  Succeeded { V } eth0:host:192.168.1.121:26066 <---> srflx:118.70.156.15:59346
STUN debug:
STUN client transactions: (1)
 method=Binding tid=11a5e00e0731d0d193ca562c rto=100ms tmr=100 n=1 interval=100

stream: mnat 'ice' connected: raddr 118.70.156.15:59346 
stream: video: starting RTCP with remote 118.70.156.15:59346
stream: video: starting mediaenc 'zrtp' (wait_secure=0)
stream: last "audio" RTP packet: 3010 milliseconds    
check_rtp: not checking (dir=inactive)
[0:00:04] audio=0/0 video=0/0 (bit/s) efps=0.0/0.0    
Peer short term public key Y is valid.
[0:00:04] audio=0/0 video=0/0 (bit/s) efps=0.0/0.0    
My   ZID:	130000004ec0093fc0a3ea4b
Peer ZID:	0100000081e62034913e16ac
Peer SAS1:	klaxon
zrtp: verify SAS <klaxon> <underfoot> for remote peer 0100000081e62034913e16ac (type /zrtp_verify 0100000081e62034913e16ac to verify)
call: mediaenc event 'Verify Request' (klaxon,underfoot,0100000081e62034913e16ac)
stream: last "audio" RTP packet: 4010 milliseconds    
check_rtp: not checking (dir=inactive)
zrtp: got security_event '16' (bit/s) efps=0.0/0.0    
stream: last "audio" RTP packet: 5010 milliseconds    
check_rtp: not checking (dir=inactive)efps=0.0/0.0    
stream: last "audio" RTP packet: 6010 milliseconds    
check_rtp: not checking (dir=inactive)efps=0.0/0.0    
stream: last "audio" RTP packet: 7010 milliseconds
...
... (No media packets sent or received)
...
```

If ZRTP is not set up, normal calls can be made between the two devices (using ICE).

**Comment by samwell-ho** [comment] 2021-09-09 10:15
From the debug information, it can be seen that the ZRTP module is loaded after loading the STUN and ICE module: 
```
...
...
...
medianat: stun
medianat: turn
medianat: ice
pcp: using PCP server at 192.168.1.1:5351
medianat: pcp
mediaenc: zrtp
...
...
...
```

**Comment by samwell-ho** [comment] 2021-09-09 10:24
@alfredh:
How can I check that after setting up ZRTP, baresip is sending media stream or not?

Apparently, before being able to set up RTP, baresip was able to send the RTP stream between the two devices. Thus, the ZTTP session can be successfully established.

**Comment by samwell-ho** [comment] 2021-09-09 10:41
@juha-h:
Have you tried if ICE + ZRTP works in some other SIP clients, such as
Linphone?

Yes, Linphone can be used with ZRTP + ICE + STUN.

**Comment by alfredh** [comment] 2021-09-10 13:42
can you please retest with git HEAD ?

**Comment by samwell-ho** [comment] 2021-09-11 00:41
@alfredh:
Sure, I'll do and let you know.

**Comment by alfredh** [comment] 2021-09-18 08:22
hi, is there any updates here ?

**Comment by alfredh** [comment] 2021-09-19 08:40
I have tested with ICE/ZRTP and Linphone, it is working here on the local network.

can you please enable in config `rtp_stats yes` and try again ?

**Comment by samwell-ho** [comment] 2021-09-20 04:24
I try with rtp_stats yes in config, but cannot send RTP if ICE is enabled. So cannot do ZRTP key exchange.

**Comment by alfredh** [comment] 2021-09-27 07:54
can you please retest with baresip command line client using latest version from GIT ?
please avoid testing custom applications and reporting issues on it.


it would be nice if you can test the following combinations of mediaenc:

- srtp
- dtls_srtp
- zrtp

please test with ICE disabled and ICE enabled.

I am wondering if there is something strange going on here:

https://github.com/baresip/baresip/blob/master/src/call.c#L517

**Comment by alfredh** [comment] 2021-09-28 21:00
also please check which Mediaenc event is coming from zrtp:

```c
$ git grep MENC_EVENT_ modules/
modules/dtls_srtp/dtls_srtp.c:                  ds->sess->eventh(MENC_EVENT_SECURE, buf,
modules/srtp/srtp.c:                    st->sess->eventh(MENC_EVENT_SECURE, buf,
modules/zrtp/zrtp.c:                            (sess->eventh)(MENC_EVENT_VERIFY_REQUEST,
modules/zrtp/zrtp.c:                            (sess->eventh)(MENC_EVENT_PEER_VERIFIED,
```

the event "Secure" is used to start media flowing, which is coming from both
the dtls_srtp and srtp module.

But the zrtp module only sends "Verify Request" and "Peer Verified" event.

perhaps something is not right here.

**Comment by alfredh** [comment] 2021-09-30 11:52
hi @samwell-ho any updates from your side ?

**Comment by alfredh** [comment] 2021-10-02 08:56
hi @samwell-ho if you report bugs, please be prepared to follow-up with testing etc.
since I dont hear anything more from you, I cannot know if you are working on this or not.
I am trying to help you, but since I hear nothing I dont know if you will provide the
additional info requested.

If you can reproduce the bug with latest version from GIT, then please create a new issue for that.
in the meantime I will close this one.

please see above for advice regarding mediaenc events.

**Closed by alfredh** 2021-10-02 08:56 UTC
